---
platform: linux

resource_types:
- name: helm
  type: docker-image
  source:
    repository: ldbl/helm-concourse-gcp
    tag: v2.8.2-helm

resources:
- name: {{release_name}}
  type: helm
  source:
    release: {{release_name}}
    cluster_url: https://kubernetes
    cluster_ca: {{cluster_ca}}
    token: {{token}}
    repos:
    - name: gcs-repo
      url: gs://((bucket))

- name: color-coded-image
  type: docker-image
  source:
    repository: gcr.io/((project))/color-coded-image
    username: _json_key
    password: {{service_account_json}}

- name: color-coded-source
  type: git
  source:
    uri: https://github.com/ldbl/color-coded.git
    branch: master
    tag_filter: v*
    username: {{git-user}}
    password: {{git-password}}

- name: chart-color-coded
  type: git
  source:
    uri: https://github.com/ldbl/chart-color-coded.git
    branch: master
    tag_filter: v*
    username: {{git-user}}
    password: {{git-password}}

- name: color-coded-dockerhub
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/color-coded-image


jobs:
  - name: build-image
    plan:
    - get: color-coded-source
      trigger: true
    - task: get-version
      file: color-coded-source/tasks/get-version.yaml
    - task: build-color-coded
      file: color-coded-source/tasks/build-color-coded.yaml
    - task: color-coded-context
      file: color-coded-source/tasks/color-coded-context.yaml
    - put: color-coded-image
      params:
        build: color-coded-context
        tag: color-coded-version/version
        tag_as_latest: true

  - name: deploy-chart
    plan:
    - get: color-coded-image
      trigger: true
      passed:
      - build-image
    - get: color-coded-source
    - task: get-version
      file: color-coded-source/tasks/get-version.yaml
    - get: chart-color-coded
      trigger: true
    - task: build-chart
      file: chart-color-coded/tasks/prep-chart.yaml
      params:
        bucket: {{bucket}}
        chart_name: {{chart_name}}
        json_key: {{service_account_json}}
    - put: {{release_name}}
      params:
        chart: gcs-repo/{{chart_name}}
        override_values:
        - key: image.repository
          path: color-coded-image/repository
        - key: image.digest
          path: color-coded-image/digest

  - name: build-and-publish-docker-image
    plan:
    - get: color-coded-source
      trigger: true
    - task: get-version
      file: color-coded-source/tasks/get-version.yaml
    - task: build-color-coded
      file: color-coded-source/tasks/build-color-coded.yaml
    - task: color-coded-context
      file: color-coded-source/tasks/color-coded-context.yaml
    - put: color-coded-dockerhub
      params:
        build: color-coded-context
        tag: color-coded-version/version
        tag_as_latest: true

