---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ldbl/concourse-go
    tag: golang-1.10.3-alpine

inputs:
- name: color-coded-source
- name: color-coded-binary

outputs:
- name: color-coded-context

run:
  path: ash
  args:
  - -exc
  - |
    pwd
    ls -la
    mkdir -p color-coded-context/bin
    cp color-coded-binary/color-coded color-coded-context/bin && cp -r color-coded-source/* color-coded-context/
    ls -la 

